version: '3'
services:
  db:
    container_name: db
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app-server:
    image: app-server:1
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /tmp/target
    ports:
      - "8080:8080"