/**
 * Truck The Line API
 * These are API docs for Truck The Line, a 48hours project led by Mark Davis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mark_davis@ultimatesoftware.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Order {
    "complete"?: boolean;
    "donationPriority"?: number;
    "id"?: number;
    "orderDate"?: Date;
    "payload"?: Array<string>;
    /**
     * Order Status
     */
    "status"?: Order.StatusEnum;
}

export namespace Order {
    export enum StatusEnum {
        SendingOrder = <any> 'Sending order',
        WaitingForTruck = <any> 'Waiting for truck',
        ReadyForPickup = <any> 'Ready for pickup'
    }
}
