/**
 * Truck The Line API
 * These are API docs for Truck The Line, a 48hours project led by Mark Davis
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mark_davis@ultimatesoftware.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Vendor {
    "complete"?: boolean;
    "donationPriority"?: number;
    "id"?: number;
    "menu"?: Array<models.Food>;
    /**
     * Vendor Status
     */
    "status"?: Vendor.StatusEnum;
}

export namespace Vendor {
    export enum StatusEnum {
        ShortWait = <any> 'Short wait',
        Busy = <any> 'Busy',
        VeryBusy = <any> 'Very Busy',
        Inactive = <any> 'Inactive'
    }
}
